CREATE TABLE gold_daily_forecast_data (
    place_name TEXT NOT NULL,
    ingest_date DATE NOT NULL,
    ingest_hour INT NOT NULL,
    forecast_date DATE NOT NULL,
    forecast_time TIME NOT NULL,
    temp_max DECIMAL(5,2),
    temp_min DECIMAL(5,2),
    temp_avg DECIMAL(5,2),
    rain_min DECIMAL(5,2),
    rain_max DECIMAL(5,2),
    rain_avg DECIMAL(5,2),
    snow_min DECIMAL(5,2),
    snow_max DECIMAL(5,2),
    snow_avg DECIMAL(5,2),
    wind_speed_min DECIMAL(5,2),
    wind_speed_max DECIMAL(5,2),
    wind_speed_avg DECIMAL(5,2),
    cloud_cover_min DECIMAL(5,2),
    cloud_cover_max DECIMAL(5,2),
    cloud_cover_avg DECIMAL(5,2),
    humidity_min DECIMAL(5,2),
    humidity_max DECIMAL(5,2),
    humidity_avg DECIMAL(5,2),
    PRIMARY KEY (place_name, forecast_date, forecast_time)
);